### ISSUE TITLE
Publish library on crates.io?

### ISSUE THREAD

**Issue by jqnatividad** [estin/geosuggest#1]
Hi @estin ,
geosuggest has not been published yet on crates.io.

It'd be great if you do as geosuggest supports updates from geonames, unlike other static reverse geocoder libraries on crates.io.

**Comment by estin** [comment]
Hi! I will try to prepare geosuggest for publish on crates.io

Before publish it needs to resolve next tasks
 - update dependencies 
 - better docs
 - example of library mode
 - index updater
 - refactor for more clear rust code (optional)

**Comment by estin** [comment]
done
