### ISSUE TITLE
Feature request: add `country_info` API

### ISSUE THREAD

**Issue by jqnatividad** [estin/geosuggest#10]
Geonames country_info is currently loaded, but only the id, code and name are used by geosuggest.

It'd be great if all the countryinfo is made available through the geosuggest API as well as the information is quite useful for data-wrangling pipelines, and is relatively small.

https://github.com/estin/geosuggest/blob/64eb0c8c43b2401a5c1f127326318994cb8187de/geosuggest-core/src/lib.rs#L121-L140

Perhaps, an API like?

```Rust
pub fn country_info(&self, country_code: &str) -> Option<&CountryRecord> {
...
}
```

**Comment by estin** [comment]
done as api. release 0.4.3

@jqnatividad do you want become collaborator for this project?
I don't rejecting this project. It's used on production and perfectly cover all cases for me.
You can start to improving it with my naive help.

**Comment by jqnatividad** [comment]
Would love to @estin! And as you're already using it for production, you can be sure I'll be sure the API remains stable and won't change without your approval.

**Comment by estin** [comment]
nice! done. you can feel free to change api too.
