### ISSUE TITLE
Feature request: Have the ability to get an Engine's configuration metadata/SourceFileOptions

### ISSUE THREAD

**Issue by jqnatividad** [estin/geosuggest#11]
It'd be great if a user can issue an API call to check an index bincode file's configuration metadata - i.e. when it was built, what languages are enabled, what Geonames URLs were used to build the index, etc. - ideally, without having to load the bincode file.

**Comment by estin** [comment]
Hi!
May be length prefix serialization for index is a good choice (don't sure).

I see the next steps in putting this agreement into action.

1) Introduce `trait IndexStorage` 

2) Store index in the next format - `<meta length><meta><payload>` for bincode to load only metadata by request.

3) Add `struct IndexMeta` with custom fields to allow users of the library set their own extra info to metadata

**Comment by jqnatividad** [comment]
That'd be great @estin !

I just did a quick and dirty JSON file serialized from IndexUpdaterSettings for my project.

But your approach is better.

BTW, speaking of bincode, have you considered using rkyv serialization for kiddo? It seems to be multiple orders of magnitude faster than bincode - https://github.com/sdd/kiddo/blob/master/CHANGELOG.md#210

**Comment by estin** [comment]
@jqnatividad Hi!

> I just did a quick and dirty JSON file serialized from IndexUpdaterSettings for my project. That's why I tweaked geosuggest-utils and released 0.4.5 (hope you don't mind!.

That is why you are a collaborator. Don't wait; release all you need.

> BTW, speaking of bincode, have you considered using rkyv serialization for kiddo? It seems to be multiple orders of magnitude faster than bincode - https://github.com/sdd/kiddo/blob/master/CHANGELOG.md#210

Don't look at. It would be nice to use more efficient serialization.

- json useful for editing index, but it is very slow to dump/load index
- bincode used only for speedup load index, especially on service startup (needs for production)

Now added
 -  `trait IndexStorage` as first step for custom serialization. It is breaking change.
 - index has metadata, and it can be read from the index file without loading the whole index.
 
And bincode serialization in the future may be enabled/disabled by feature flags.

Check https://github.com/estin/geosuggest/blob/master/geosuggest-core/src/storage.rs
